[package]
name = "stress_tester"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stress_tester"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.31", default-features = true }

[dependencies.windows]
version = "0.58"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Diagnostics_ToolHelp",
]
