[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "capture_bypass_gui"
path = "src/main.rs"

[dependencies]
eframe        = { version = "0.31", default-features = true }
egui_extras   = { version = "0.31", features = ["tables"] }
injector_core = { path = "../core" }
tray-icon     = { version = "0.19", features = ["common-controls"] }

[dependencies.windows]
version = "0.58"
features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Diagnostics_ToolHelp",
]

[build-dependencies]
winres = "0.1"
